SEND_BYTES = BYTES = 0
SEND_TEXT = TEXT = 1
SEND_FILE = 3
SEND_LIST = LIST = 4
SEND_OBJECT = OBJECT = 5
SEND_COMPLETE_FILE = FILE = 6
SAVED_FILE = 7

SEND_CERTIFICATE = 0
CERT_FAILED = 1
CERT_SUCCEEDED = 2
SEND_SESSION_KEY = 3